package uebung02.a4.adressbuch;


/**
* uebung02/a4/adressbuch/_AdressbuchStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from ../libs/a4/adressbuch.idl
* Mittwoch, 26. November 2003 20.50 Uhr CET
*/

public class _AdressbuchStub extends org.omg.CORBA.portable.ObjectImpl implements uebung02.a4.adressbuch.Adressbuch
{

  public void store (uebung02.a4.adressbuch.Adresse adr)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("store", true);
                uebung02.a4.adressbuch.AdresseHelper.write ($out, adr);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                store (adr        );
            } finally {
                _releaseReply ($in);
            }
  } // store

  public uebung02.a4.adressbuch.Adresse search (uebung02.a4.adressbuch.SearchParam param, String searchstr)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("search", true);
                uebung02.a4.adressbuch.SearchParamHelper.write ($out, param);
                $out.write_wstring (searchstr);
                $in = _invoke ($out);
                uebung02.a4.adressbuch.Adresse $result = uebung02.a4.adressbuch.AdresseHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return search (param, searchstr        );
            } finally {
                _releaseReply ($in);
            }
  } // search

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:adressbuch/Adressbuch:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.Object obj = org.omg.CORBA.ORB.init (args, props).string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     String str = org.omg.CORBA.ORB.init (args, props).object_to_string (this);
     s.writeUTF (str);
  }
} // class _AdressbuchStub
