package uebung02.a4.adressbuch;


/**
* adressbuch/AdressbuchHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from adressbuch.idl
* Samstag, 22. November 2003 16.13 Uhr CET
*/

abstract public class AdressbuchHelper
{
  private static String  _id = "IDL:adressbuch/Adressbuch:1.0";

  public static void insert (org.omg.CORBA.Any a, Adressbuch that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static Adressbuch extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (AdressbuchHelper.id (), "Adressbuch");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static Adressbuch read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_AdressbuchStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, Adressbuch value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static Adressbuch narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Adressbuch)
      return (Adressbuch)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      _AdressbuchStub stub = new _AdressbuchStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
