package uebung02.a4.adressbuch;

/**
* uebung02/a4/adressbuch/AdresseHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from ../libs/a4/adressbuch.idl
* Mittwoch, 26. November 2003 20.50 Uhr CET
*/

public final class AdresseHolder implements org.omg.CORBA.portable.Streamable
{
  public uebung02.a4.adressbuch.Adresse value = null;

  public AdresseHolder ()
  {
  }

  public AdresseHolder (uebung02.a4.adressbuch.Adresse initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = uebung02.a4.adressbuch.AdresseHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    uebung02.a4.adressbuch.AdresseHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return uebung02.a4.adressbuch.AdresseHelper.type ();
  }

}
