package uebung02.a4.adressbuch;


/**
* uebung02/a4/adressbuch/Adresse.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from ../libs/a4/adressbuch.idl
* Mittwoch, 26. November 2003 20.50 Uhr CET
*/

public final class Adresse implements org.omg.CORBA.portable.IDLEntity
{
  public String Name = null;
  public String Strasse = null;
  public short HausNr = (short)0;
  public int PLZ = (int)0;
  public String Stadt = null;

  public Adresse ()
  {
  } // ctor

  public Adresse (String _Name, String _Strasse, short _HausNr, int _PLZ, String _Stadt)
  {
    Name = _Name;
    Strasse = _Strasse;
    HausNr = _HausNr;
    PLZ = _PLZ;
    Stadt = _Stadt;
  } // ctor

} // class Adresse
