package uebung02.a4.adressbuch;


/**
* uebung02/a4/adressbuch/Adressbuch.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from ../libs/a4/adressbuch.idl
* Mittwoch, 10. Dezember 2003 18.19 Uhr CET
*/

public interface Adressbuch extends AdressbuchOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Adressbuch
