package uebung02.a4.adressbuch;

/**
* adressbuch/AdressbuchHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from adressbuch.idl
* Samstag, 22. November 2003 16.13 Uhr CET
*/

public final class AdressbuchHolder implements org.omg.CORBA.portable.Streamable
{
  public Adressbuch value = null;

  public AdressbuchHolder ()
  {
  }

  public AdressbuchHolder (Adressbuch initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = AdressbuchHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    AdressbuchHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return AdressbuchHelper.type ();
  }

}
