package uebung02.a4.adressbuch;

/**
* uebung02/a4/adressbuch/SearchParamHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from ../libs/a4/adressbuch.idl
* Mittwoch, 26. November 2003 20.50 Uhr CET
*/

public final class SearchParamHolder implements org.omg.CORBA.portable.Streamable
{
  public uebung02.a4.adressbuch.SearchParam value = null;

  public SearchParamHolder ()
  {
  }

  public SearchParamHolder (uebung02.a4.adressbuch.SearchParam initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = uebung02.a4.adressbuch.SearchParamHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    uebung02.a4.adressbuch.SearchParamHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return uebung02.a4.adressbuch.SearchParamHelper.type ();
  }

}
