package uebung02.a4.adressbuch;


/**
* uebung02/a4/adressbuch/SearchParam.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from ../libs/a4/adressbuch.idl
* Mittwoch, 26. November 2003 20.50 Uhr CET
*/

public class SearchParam implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 3;
  private static uebung02.a4.adressbuch.SearchParam[] __array = new uebung02.a4.adressbuch.SearchParam [__size];

  public static final int _NAME = 0;
  public static final uebung02.a4.adressbuch.SearchParam NAME = new uebung02.a4.adressbuch.SearchParam(_NAME);
  public static final int _STRASSE = 1;
  public static final uebung02.a4.adressbuch.SearchParam STRASSE = new uebung02.a4.adressbuch.SearchParam(_STRASSE);
  public static final int _STADT = 2;
  public static final uebung02.a4.adressbuch.SearchParam STADT = new uebung02.a4.adressbuch.SearchParam(_STADT);

  public int value ()
  {
    return __value;
  }

  public static uebung02.a4.adressbuch.SearchParam from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected SearchParam (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class SearchParam
