package netprog.uebung02.a3.repstring;


/**
 * netprog/uebung02/a3/repstring/replicatedstringOperations.java .
 * Generated by the IDL-to-Java compiler (portable), version "3.1"
 * from repstring.idl
 * Donnerstag, 20. November 2003 16.26 Uhr CET
 */

public interface replicatedstringOperations
{
    void set(String s);

    String get();

    void replicateAt(netprog.uebung02.a3.repstring.replicatedstring rs);
} // interface replicatedstringOperations
