package uebung02.a1_2.adder;

/**
* uebung02/a1_2/adder/floataddHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from ../libs/a1_2/adder.idl
* Mittwoch, 26. November 2003 20.50 Uhr CET
*/

public final class floataddHolder implements org.omg.CORBA.portable.Streamable
{
  public uebung02.a1_2.adder.floatadd value = null;

  public floataddHolder ()
  {
  }

  public floataddHolder (uebung02.a1_2.adder.floatadd initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = uebung02.a1_2.adder.floataddHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    uebung02.a1_2.adder.floataddHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return uebung02.a1_2.adder.floataddHelper.type ();
  }

}
