package uebung02.a1_2.adder;


/**
* uebung02/a1_2/adder/floataddOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from ../libs/a1_2/adder.idl
* Mittwoch, 10. Dezember 2003 18.19 Uhr CET
*/

public interface floataddOperations 
{
  void sum (org.omg.CORBA.DoubleHolder a, double b);
} // interface floataddOperations
