package uebung02.a1_2.adder;


/**
* uebung02/a1_2/adder/floatadd.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from ../libs/a1_2/adder.idl
* Mittwoch, 26. November 2003 20.50 Uhr CET
*/

public interface floatadd extends floataddOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface floatadd
