package uebung02.a1_2.adder;


/**
 * netprog/uebung02/a1_2/adder/floatadd.java .
 * Generated by the IDL-to-Java compiler (portable), version "3.1"
 * from adder.idl
 * Dienstag, 18. November 2003 23.32 Uhr CET
 */

public interface floatadd extends floataddOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity
{
} // interface floatadd
