package uebung02.a3.repstring;

/**
 * netprog/uebung02/a3/repstring/replicatedstringHolder.java .
 * Generated by the IDL-to-Java compiler (portable), version "3.1"
 * from repstring.idl
 * Donnerstag, 20. November 2003 16.26 Uhr CET
 */

public final class replicatedstringHolder implements org.omg.CORBA.portable.Streamable
{
    public uebung02.a3.repstring.replicatedstring value = null;

    public replicatedstringHolder()
    {
    }

    public replicatedstringHolder(uebung02.a3.repstring.replicatedstring initialValue)
    {
        value = initialValue;
    }

    public void _read(org.omg.CORBA.portable.InputStream i)
    {
        value = uebung02.a3.repstring.replicatedstringHelper.read(i);
    }

    public void _write(org.omg.CORBA.portable.OutputStream o)
    {
        uebung02.a3.repstring.replicatedstringHelper.write(o, value);
    }

    public org.omg.CORBA.TypeCode _type()
    {
        return uebung02.a3.repstring.replicatedstringHelper.type();
    }

}
