package uebung02.a3.repstring;


/**
* uebung02/a3/repstring/replicatedstringOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from ../libs/a3/repstring.idl
* Mittwoch, 10. Dezember 2003 18.19 Uhr CET
*/

public interface replicatedstringOperations 
{
  void set (String s);
  String get ();
  void replicateAt (uebung02.a3.repstring.replicatedstring rs);
} // interface replicatedstringOperations
