package netprog.uebung02.a1_2.adder;


/**
 * netprog/uebung02/a1_2/adder/floataddPOA.java .
 * Generated by the IDL-to-Java compiler (portable), version "3.1"
 * from adder.idl
 * Dienstag, 18. November 2003 23.32 Uhr CET
 */

public abstract class floataddPOA extends org.omg.PortableServer.Servant
implements netprog.uebung02.a1_2.adder.floataddOperations, org.omg.CORBA.portable.InvokeHandler
{

    // Constructors

    private static java.util.Hashtable _methods = new java.util.Hashtable();

    static
    {
        _methods.put("sum", new java.lang.Integer(0));
    }

    public org.omg.CORBA.portable.OutputStream _invoke(String $method,
                                                       org.omg.CORBA.portable.InputStream in,
                                                       org.omg.CORBA.portable.ResponseHandler $rh)
    {
        org.omg.CORBA.portable.OutputStream out = null;
        java.lang.Integer __method = (java.lang.Integer)_methods.get($method);
        if (__method == null)
            throw new org.omg.CORBA.BAD_OPERATION(0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

        switch (__method.intValue())
        {
            case 0:  // adder/floatadd/sum
                {
                    org.omg.CORBA.DoubleHolder a = new org.omg.CORBA.DoubleHolder();
                    a.value = in.read_double();
                    double b = in.read_double();
                    this.sum(a, b);
                    out = $rh.createReply();
                    out.write_double(a.value);
                    break;
                }

            default:
                throw new org.omg.CORBA.BAD_OPERATION(0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
        }

        return out;
    } // _invoke

    // Type-specific CORBA::Object operations
    private static String[] __ids = {
        "IDL:adder/floatadd:1.0"};

    public String[] _all_interfaces(org.omg.PortableServer.POA poa, byte[] objectId)
    {
        return (String[])__ids.clone();
    }

    public floatadd _this()
    {
        return floataddHelper.narrow(
        super._this_object());
    }

    public floatadd _this(org.omg.CORBA.ORB orb)
    {
        return floataddHelper.narrow(
        super._this_object(orb));
    }


} // class floataddPOA
