package netprog.uebung02.a1_2.adder;


/**
* netprog/uebung02/a1_2/adder/floataddOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from adder.idl
* Dienstag, 18. November 2003 23.32 Uhr CET
*/

public interface floataddOperations 
{
  void sum (org.omg.CORBA.DoubleHolder a, double b);
} // interface floataddOperations
