package netprog.uebung02.a4.adressbuch;


/**
* adressbuch/AdressbuchPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from adressbuch.idl
* Samstag, 22. November 2003 16.13 Uhr CET
*/

public abstract class AdressbuchPOA extends org.omg.PortableServer.Servant
 implements AdressbuchOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("store", new java.lang.Integer (0));
    _methods.put ("search", new java.lang.Integer (1));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // adressbuch/Adressbuch/store
       {
         Adresse adr = AdresseHelper.read (in);
         this.store (adr);
         out = $rh.createReply();
         break;
       }

       case 1:  // adressbuch/Adressbuch/search
       {
         SearchParam param = SearchParamHelper.read (in);
         String searchstr = in.read_wstring ();
         Adresse $result = null;
         $result = this.search (param, searchstr);
         out = $rh.createReply();
         AdresseHelper.write (out, $result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:adressbuch/Adressbuch:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Adressbuch _this() 
  {
    return AdressbuchHelper.narrow(
    super._this_object());
  }

  public Adressbuch _this(org.omg.CORBA.ORB orb) 
  {
    return AdressbuchHelper.narrow(
    super._this_object(orb));
  }


} // class AdressbuchPOA
