package netprog.uebung02.a4.adressbuch;


/**
* adressbuch/AdressbuchOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from adressbuch.idl
* Samstag, 22. November 2003 16.13 Uhr CET
*/

public interface AdressbuchOperations 
{
  void store (Adresse adr);
  Adresse search (SearchParam param, String searchstr);
} // interface AdressbuchOperations
