package adressbuch;

/**
* adressbuch/AdresseHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from adressbuch.idl
* Samstag, 22. November 2003 16.13 Uhr CET
*/

public final class AdresseHolder implements org.omg.CORBA.portable.Streamable
{
  public adressbuch.Adresse value = null;

  public AdresseHolder ()
  {
  }

  public AdresseHolder (adressbuch.Adresse initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = adressbuch.AdresseHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    adressbuch.AdresseHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return adressbuch.AdresseHelper.type ();
  }

}
