package netprog.uebung02.a4.adressbuch;

/**
* adressbuch/SearchParamHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from adressbuch.idl
* Samstag, 22. November 2003 16.13 Uhr CET
*/

public final class SearchParamHolder implements org.omg.CORBA.portable.Streamable
{
  public SearchParam value = null;

  public SearchParamHolder ()
  {
  }

  public SearchParamHolder (SearchParam initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = SearchParamHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    SearchParamHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return SearchParamHelper.type ();
  }

}
