package adressbuch;


/**
* adressbuch/SearchParam.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from adressbuch.idl
* Samstag, 22. November 2003 16.13 Uhr CET
*/

public class SearchParam implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 3;
  private static adressbuch.SearchParam[] __array = new adressbuch.SearchParam [__size];

  public static final int _NAME = 0;
  public static final adressbuch.SearchParam NAME = new adressbuch.SearchParam(_NAME);
  public static final int _STRASSE = 1;
  public static final adressbuch.SearchParam STRASSE = new adressbuch.SearchParam(_STRASSE);
  public static final int _STADT = 2;
  public static final adressbuch.SearchParam STADT = new adressbuch.SearchParam(_STADT);

  public int value ()
  {
    return __value;
  }

  public static adressbuch.SearchParam from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected SearchParam (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class SearchParam
